Repository openshift/jenkins-sync-plugin, pull requests merged in 2018-05, with the labels that each got.

#237 Add support for syncing certificate type credentials.
  README.md
  src/main/java/io/fabric8/jenkins/openshiftsync/Constants.java
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, size/M

#238 Updating to latest OpenShift Client
  pom.xml
Labels: approved, lgtm, size/XS

#239 Fixed the issue of duplicate pipeline
  src/main/java/io/fabric8/jenkins/openshiftsync/Constants.java
  src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java
  velocity.log
Labels: approved, lgtm, size/L
