Repository openshift/jenkins-sync-plugin, pull requests merged in 2018-03, with the labels that each got.

#213 Bootstrap an OWNERS file
  OWNERS
Labels: lgtm, size/XS

#199 Delete Jenkins job run when build is deleted from OpenShift
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/M

#214 more logging around closed watches; lazy reconnect on closed watch
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/WatcherCallback.java
Labels: approved, lgtm, size/L
