Repository openshift/jenkins-sync-plugin, pull requests merged in 2018-08, with the labels that each got.

#250 Fix env vars from JenkinsPipelineBuildStrategy could be null values
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/S

#252 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#254 Fix duplicate job run parameters
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/S

#256 Additional fix of the null parameter issue
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/XS

#258 adjust secret/credential mapping to account for optional secret type …
  pom.xml
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, size/XL
