Repository openshift/jenkins-sync-plugin, pull requests merged in 2018-12, with the labels that each got.

#275 pom.xml - update cloudbees-folder version to 6.6
  pom.xml
Labels: approved, lgtm, ok-to-test, size/XS

#276 better handle temporary flownode unavailability (they evidently can b…
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/M

#277 Add version commits
  pom.xml
Labels: approved, lgtm, size/XS
