Repository openshift/jenkins-sync-plugin, pull requests merged in 2018-04, with the labels that each got.

#215 Flush the build HashSet directly without clone it.
  pom.xml
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
Labels: approved, lgtm, size/M

#217 some cleanup to flushBuildsWithNoBCList optimization
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
Labels: approved, size/S

#218 impl cache hit for job from bc from build lookup
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMap.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, size/M

#219 Cfg list interval
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretWatcher.java
  src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly
Labels: approved, lgtm, size/L

#221 switch watcher map to Concurrent, clear out after loop to close vs. i…
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
Labels: approved, lgtm, size/XS

#222 Add sync of Openshift opaque secrets to Jenkins file credentials
  README.md
  pom.xml
  src/main/java/io/fabric8/jenkins/openshiftsync/Constants.java
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, size/M

#223 Reconcile running on non-openshift pipeline builds
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
Labels: approved, lgtm, size/S

#224 Jenkins job run delete delayed
  src/main/java/io/fabric8/jenkins/openshiftsync/Annotations.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/S

#225 buildConfigPropertyForJob does not loop through all namespaces
  src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java
  src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java
Labels: approved, lgtm, size/M

#228 bump okhttp max concurrent watch conns past 5 total
  src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java
Labels: approved, lgtm, size/XS

#229 Fixing namespace could be null
  src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java
Labels: approved, lgtm, size/XS

#231 Adding foldersEnabled field to global configuration
  src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java
  src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java
  src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/config.jelly
  src/main/resources/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration/help-foldersEnabled.html
  src/test/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtilsTest.java
Labels: approved, lgtm, size/M

#234 unblocking - use java.concurrent without blocking.
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMap.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretWatcher.java
Labels: approved, lgtm, size/L

#235 do not update build repeatedly if paused for update
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java
Labels: approved, lgtm, size/XS
