Repository openshift/jenkins-sync-plugin, pull requests merged in 2019-10, with the labels that each got.

#346 Refactor of ImageStreamWatcher
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
Labels: approved, lgtm, size/L

#347 Adds sbose78, akashshinde otaviof to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#348 Refactored to have all PodTemplate related funnctionality in PodTemplateUtils
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
  src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java
  src/main/java/io/fabric8/jenkins/openshiftsync/PodTemplateUtils.java
Labels: approved, lgtm, size/XL

#349 Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10
  pom.xml
Labels: approved, lgtm, size/XS

#354 Use password (if available) when adding SSH private keys
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, ok-to-test, size/XS

#357 Add passphrase support
  src/main/java/io/fabric8/jenkins/openshiftsync/Constants.java
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, size/M

#356 Universal redeploy script
  deploy.sh
Labels: approved, lgtm, size/S

#358 Add the team as reviewers
  OWNERS
Labels: approved, lgtm, size/XS
