Repository openshift/jenkins-sync-plugin, pull requests merged in 2019-09, with the labels that each got.

#335 "Fix for fraternal twin secrets creation upon applying secret.name annotation"
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretWatcher.java
Labels: approved, lgtm, size/L

#337 Fix secretUid to Name mapping
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
Labels: approved, lgtm, size/S

#339 Cleaning GlobalPluginConfiguration, extract variables, add this keyword when n…
  src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfiguration.java
Labels: approved, lgtm, size/L

#341 Bug 1755812: Refactor and allow for updating configmaps to sync PodTemplates dynamically
  src/main/java/io/fabric8/jenkins/openshiftsync/BaseWatcher.java
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#343 New development iteration for 1.0.43
  pom.xml
Labels: approved, lgtm, size/XS

#342 Update with New Maintainers
  MAINTAINERS
Labels: approved, lgtm, size/XS
