Repository openshift/jenkins-sync-plugin, pull requests merged in 2019-03, with the labels that each got.

#287 NPE on Bluerun.getNodes().iterator()
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java
Labels: approved, lgtm, ok-to-test, size/XS

#288 massage doc around custom name for secret to credential
  README.md
Labels: approved, lgtm, size/XS

#289 Bump version
  pom.xml
Labels: approved, lgtm, size/XS

#290 Add adambkaplan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#292 Bump version
  pom.xml
Labels: approved, lgtm, size/XS

#294 create Dockerfile to enable prow based PR jobs against v4.x clusters
  Dockerfile
Labels: approved, lgtm, size/S

#297 check ist labels as well in case inherited from is
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
Labels: approved, lgtm, size/S

#298 Bump version
  pom.xml
Labels: approved, lgtm, size/XS

#299 README clarifications on is/ist image for pod templates; add ist labe…
  README.md
Labels: approved, lgtm, size/S
