Repository openshift/jenkins-sync-plugin, pull requests merged in 2019-07, with the labels that each got.

#317 synchronization fixes for recently discovered deadlock
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigSecretToCredentialsMap.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java
  src/main/java/io/fabric8/jenkins/openshiftsync/JenkinsUtils.java
Labels: approved, lgtm, size/L

#318 Bump jenkins-sync-plugin Version to 1.0.39
  pom.xml
Labels: approved, lgtm, size/XS

#319 add devtools to owners
  OWNERS
Labels: approved, lgtm, size/XS

#320 Bug 1711533: Bump kubernetes-client version (openshift-client) to 4.3 to support O…
  pom.xml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
