Repository openshift/jenkins-sync-plugin, pull requests merged in 2022-01, with the labels that each got.

#410 Bug 2034839: Watch ConfigMap and ImageStream also with the legacy label
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/Constants.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/PodTemplateUtils.java
  test/e2e/sync_plugin_test.go
  test/e2e/testobjects.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#411 Catch up
  pom.xml
Labels: lgtm, approved

#413 move from nodejs:12 to nodejs:latest since 12 is EOL an no longer in nodejs IS
  test/e2e/testobjects.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#415 pull in upstream commits from release 1.0.53 generation
  pom.xml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
