Repository openshift/jenkins-sync-plugin, pull requests merged in 2022-03, with the labels that each got.

#418 Bug 2064139: Fix configmap update bug that constantly purges templates with no changes
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapInformer.java
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-unspecified, px-approved, docs-approved

#420 JKNS-267: check JENKINS-IMAGE existence, tag into jenkins imagestream, from Makefile test-e2e
  Makefile
  hack/tag-ci-image.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#417 Fixed improperly formatted logger statements
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/BuildInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ConfigMapInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/GlobalPluginConfigurationTimerTask.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/PodTemplateUtils.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretClusterInformer.java
  src/main/java/io/fabric8/jenkins/openshiftsync/SecretInformer.java
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved
